eureka:
  instance:
  prefer-ip-address: true
  instance-id : ${spring.cloud.client.ip-address}:${server.port}
  hostname:  localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  

spring:
  datasource:
    hikari:
      maximum-pool-size: 8
    url:  jdbc:mysql://localhost:3306/springcloudeureka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  config:
    import: "optional:configserver:"
       
    
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
  default_schema: test
  format_sql: true
  generate_statistics: true
  dialect: org.hibernate.dialect.MySQL8Dialect
  dialect.storage_engine: innodb

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri:
          -http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri:
          -http://ORDER-SERVICE/order/bookOrder
